
1. Scenario: A company wants to analyze the sales performance of its products in different regions. They have collected the following data:
  - Region A: [10, 15, 12, 8, 14]
  - Region B: [18, 20, 16, 22, 25]
  - Calculate the mean sales for each region.

In [1]:
import pandas as pd
import numpy as np

In [2]:
Region_A = [10, 15, 12, 8, 14]
Region_B = [18, 20, 16, 22, 25]

In [3]:
mean_A=np.mean(Region_A)
mean_B=np.mean(Region_B)

In [4]:
print(f"Mean of Region A is {mean_A}")
print(f"Mean of Region B is {mean_B}")

Mean of Region A is 11.8
Mean of Region B is 20.2


2. Scenario: A survey is conducted to measure customer satisfaction on a scale of 1 to 5. The data collected is as follows:
   - [4, 5, 2, 3, 5, 4, 3, 2, 4, 5]
   - Calculate the mode of the survey responses.


In [5]:
Ratings=[4, 5, 2, 3, 5, 4, 3, 2, 4, 5]

In [6]:
df=pd.DataFrame(Ratings,columns=['Customer_Satisfaction'])

In [7]:
mode=df['Customer_Satisfaction'].mode()[0]

In [8]:
print(f" Mode of Customer Satisfaction is {mode}")

 Mode of Customer Satisfaction is 4


3. Scenario: A company wants to compare the salaries of two departments. The salary data for Department A and Department B are as follows:
   - Department A: [5000, 6000, 5500, 7000]
   - Department B: [4500, 5500, 5800, 6000, 5200]
   - Calculate the median salary for each department.


In [9]:
Department_A= [5000, 6000, 5500, 7000]
Department_B=[4500, 5500, 5800, 6000, 5200]

In [10]:
median_A=np.median(Department_A)
median_B=np.median(Department_B)

In [11]:
print("Median of Department_A is {}".format(median_A))
print("Median of Department_B is {}".format(median_B))

Median of Department_A is 5750.0
Median of Department_B is 5500.0


4. Scenario: A data analyst wants to determine the variability in the daily stock prices of a company. The data collected is as follows:
   - [25.5, 24.8, 26.1, 25.3, 24.9]
   - Calculate the range of the stock prices


In [12]:
Stock_price=[25.5, 24.8, 26.1, 25.3, 24.9]

In [13]:
Range=max(Stock_price)-min(Stock_price)

In [14]:
Range

1.3000000000000007

5. Scenario: A study is conducted to compare the performance of two different teaching methods. The test scores of the students in each group are as follows:
   - Group A: [85, 90, 92, 88, 91]
   - Group B: [82, 88, 90, 86, 87]
   - Perform a t-test to determine if there is a significant difference in the mean scores between the two groups


In [15]:
Group_A= [85, 90, 92, 88, 91]
Group_B= [82, 88, 90, 86, 87]


In [16]:
mean_A=np.mean(Group_A)
mean_B=np.mean(Group_B)

In [17]:
print(f"Mean A is {mean_A} and mean of B is {mean_B}")

Mean A is 89.2 and mean of B is 86.6


In [18]:
## lets consider significance level to  be 5%
## Confidence Iterval=95%

In [19]:
## lets check from t-table what is critical value corresponds to 0.025 as two tailed (significace level/2)

In [20]:
## Critical value found fro table is 2.776 
Critical_value=2.776

In [21]:
std_A=np.std(Group_A)
std_B=np.std(Group_B)

In [22]:
print(f"STD of A is {std_A} and for B is {std_B}")

STD of A is 2.4819347291981715 and for B is 2.6532998322843198


In [23]:
t_stats=(mean_A-mean_B)/(std_A/np.sqrt(5)+std_B/np.sqrt(5))

In [24]:
t_stats

1.132134602985125

In [25]:
if t_stats>Critical_value:
    print("There is significant difference between samples and we reject the null hypothesis")
else:
    print("There is not much significance difference so we accept the null hypothesis")

There is not much significance difference so we accept the null hypothesis


6. Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:
   - Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]
   - Sales (in thousands): [25, 30, 28, 20, 26]
   - Calculate the correlation coefficient between advertising expenditure and sales.


In [26]:
Advertising_Expenditure = [10, 15, 12, 8, 14]
Sales = [25, 30, 28, 20, 26]

In [27]:
df_advert_sales=pd.DataFrame({'Advertising_Expenditure':Advertising_Expenditure,'Sales':Sales})

In [28]:
df_advert_sales.corr()

Advertising_Expenditure     Sales
Advertising_Expenditure                 1.000000  0.875751
Sales                                   0.875751  1.000000

7. Scenario: A survey is conducted to measure the heights of a group of people. The data collected is as follows:
   - [160, 170, 165, 155, 175, 180, 170]
   - Calculate the standard deviation of the heights.


In [29]:
mean= sum([160, 170, 165, 155, 175, 180, 170])/7

In [30]:
var=((160-mean)**2+(170-mean)**2+(165-mean)**2+(155-mean)**2+(175-mean)**2+(180-mean)**2+(170-mean)**2)/7

In [31]:
std=np.sqrt(var)

In [32]:
print("Standard Deviation of heights is {}".format(std))

Standard Deviation of heights is 7.953949089757174


In [33]:
np.std([160, 170, 165, 155, 175, 180, 170])

7.953949089757174

8. Scenario: A company wants to analyze the relationship between employee tenure and job satisfaction. The data collected is as follows:
   - Employee Tenure (in years): [2, 3, 5, 4, 6, 2, 4]
   - Job Satisfaction (on a scale of 1 to 10): [7, 8, 6, 9, 5, 7, 6]
   - Perform a linear regression analysis to predict job satisfaction based on employee tenure.


In [34]:
Employee_Tenure = [2, 3, 5, 4, 6, 2, 4]
Job_Satisfaction = [7, 8, 6, 9, 5, 7, 6]

In [35]:
from sklearn.linear_model import LinearRegression

In [36]:
df=pd.DataFrame({'Employee_Tenure':Employee_Tenure,'Job_Satisfaction':Job_Satisfaction})

In [37]:
df

Employee_Tenure  Job_Satisfaction
0                2                 7
1                3                 8
2                5                 6
3                4                 9
4                6                 5
5                2                 7
6                4                 6

In [38]:
LR=LinearRegression()

In [39]:
X=df[['Employee_Tenure']]

In [40]:
y=df['Job_Satisfaction']

In [41]:
LR.fit(X,y)

LinearRegression()

In [42]:
## Lets Consider Employee Tenure for 1 and 7 years to predict Job Satisfaction
predict_data=pd.DataFrame({'Employee_Tenure':[1,7]})

In [43]:
LR.predict(predict_data)

array([8.12765957, 5.31914894])

9. Scenario: A study is conducted to compare the effectiveness of two different medications. The recovery times of the patients in each group are as follows:
   - Medication A: [10, 12, 14, 11, 13]
   - Medication B: [15, 17, 16, 14, 18]
   - Perform an analysis of variance (ANOVA) to determine if there is a significant difference in the mean recovery times between the two medications


In [44]:
import scipy.stats as stat

In [45]:
Medication_A=[10, 12, 14, 11, 13]
Medication_B=[15, 17, 16, 14, 18]

In [46]:
## State Null and alternate Hypothesis 
## H0:u1=u2 meaning mean recovery time is same for both medicine
## H1:u1!=u2

In [47]:
## Consider Significance level of 5%
## Confidence Interval :95%

In [48]:
alpha=.05

In [49]:
## Calculate Degree of Freedom

In [50]:
N=10  
a=2
n=5

In [51]:
df_between=a-1
df_between

1

In [52]:
df_within=N-a
df_within

8

In [53]:
## Decision Boundary
## We need to calculate critical value at alpha=.05 from F-Table considering df_between and df_within

In [54]:
Critical_value=5.32

In [55]:
## Calculate F _test statistic

In [56]:
sum_of_squares_between=((sum(Medication_A)**2 +sum(Medication_B)**2)/5)-(sum(Medication_A)+sum(Medication_B))**2/10

In [57]:
sum_of_squares_between

40.0

In [58]:
sum_of_squares_within=(10**2+12**2+14**2+11**2+13**2+15**2+17**2+16**2+14**2+18**2)-(sum(Medication_A)**2 +sum(Medication_B)**2)/5

In [59]:
sum_of_squares_within

20.0

In [60]:
Mean_Square_between=sum_of_squares_between/df_between
Mean_Square_within=sum_of_squares_within/df_within

In [61]:
F_test=Mean_Square_between/Mean_Square_within

In [62]:
F_test

16.0

In [63]:
## Clearly F_test is greater than critical value so we reject the null hypothesis

In [64]:
if F_test>Critical_value:
    print("Null Hypthesis is rejected and recovery time for second medication is higher")
else:
    print("Null Hypothesis is accepted and recovery time is same for both medicine")

Null Hypthesis is rejected and recovery time for second medication is higher


10. Scenario: A company wants to analyze customer feedback ratings on a scale of 1 to 10. The data collected is

 as follows:
- [8, 9, 7, 6, 8, 10, 9, 8, 7, 8]
- Calculate the 75th percentile of the feedback ratings.


In [65]:
data=[8, 9, 7, 6, 8, 10, 9, 8, 7, 8]

In [66]:
percentile_75=np.percentile(data,75)

In [67]:
percentile_75

8.75

11. Scenario: A quality control department wants to test the weight consistency of a product. The weights of a sample of products are as follows:
- [10.2, 9.8, 10.0, 10.5, 10.3, 10.1]
- Perform a hypothesis test to determine if the mean weight differs significantly from 10 grams.


In [68]:
data=[10.2, 9.8, 10.0, 10.5, 10.3, 10.1]

In [69]:
mean_data=np.mean(data)

In [70]:
mean_data

10.15

In [71]:
std_data=np.std(data)

In [72]:
std_data

0.22173557826083437

In [73]:
## H0:u1=10
## H1:u1!=10

In [74]:
## Consider significance level of 5%
aplha=.05

In [75]:
## Degree of freedom
df=5

In [76]:
## At alpha :0.05 critical value from t_table
critical_value=2.571

In [77]:
## Calculate T_value

In [78]:
t_value=(mean_data-10)/(std_data/np.sqrt(6))

In [79]:
t_value

1.657034312216987

In [80]:
##
if t_value>critical_value:
    print("we reject the null hypothesis and there is significant diference in mean")
else:
    print("We fail to reject the null hypotesis and  do not have enough evidence to conclude that the mean weight significantly differs from 10 grams")

We fail to reject the null hypotesis and  do not have enough evidence to conclude that the mean weight significantly differs from 10 grams


12. Scenario: A company wants to analyze the click-through rates of two different website designs. The number of clicks for each design is as follows:
- Design A: [100, 120, 110, 90, 95]
- Design B: [80, 85, 90, 95, 100]
- Perform a chi-square test to determine if there is a significant difference in the click-through rates between the two designs


In [81]:
Design_A= [100, 120, 110, 90, 95]
Design_B= [80, 85, 90, 95, 100]

In [82]:
import scipy.stats as stat

In [83]:
## H0:u1=u2
## H1:u1!=u2

In [84]:
## Significance level:0.05
alpha=.05

In [85]:
## Degree of Freedom
df=2-1  ## 2 categories

In [86]:
## Critcal Value from chi square table for alpha=0.05 and df=1  is
critical_value=3.841

In [87]:
## Calculate Chi Square Statistic
chi_sq_statistic=((100-80)**2/100+(120-85)**2/120+(110-90)**2/110+(90-95)**2/90+(95-100)**2/95)

In [88]:
chi_sq_statistic

18.38563264221159

In [89]:
if chi_sq_statistic>critical_value:
    print("We Reject the null hypothesis and there is significant diference in the click through rates")
else:
    print("We Accept the null hypothesis and there is not any significant diference in the click through rates")

We Reject the null hypothesis and there is significant diference in the click through rates


13. Scenario: A survey is conducted to measure customer satisfaction with a product on a scale of 1 to 10. The data collected is as follows:
- [7, 9, 6, 8, 10, 7, 8, 9, 7, 8]
- Calculate the 95% confidence interval for the population mean satisfaction score.


In [90]:
data= [7, 9, 6, 8, 10, 7, 8, 9, 7, 8]

In [91]:
mean_data=np.mean(data)

In [92]:
std_data=np.std(data)

In [93]:
standard_error=std_data/np.sqrt(len(data))

In [94]:
standard_error

0.3591656999213594

In [95]:
## For confidence interval of 95% critical value for two tail is found to be
critical_value=1.96

In [96]:
#Calculate the margin of error (ME) by multiplying the critical value by the standard error:
ME = critical_value * standard_error 

In [97]:
ME

0.7039647718458644

In [98]:
lower_bound=mean_data-ME
upper_bound=mean_data+ME

In [99]:
print(f"Lower Bound        :    upper bound '\n'{lower_bound} :{upper_bound}")

Lower Bound        :    upper bound '
'7.196035228154136 :8.603964771845865


14. Scenario: A company wants to analyze the effect of temperature on product performance. The data collected is as follows:
- Temperature (in degrees Celsius): [20, 22, 23, 19, 21]
- Performance (on a scale of 1 to 10): [8, 7, 9, 6, 8]
- Perform a simple linear regression to predict performance based on temperature


In [100]:
Temperature = [20, 22, 23, 19, 21]
Performance = [8, 7, 9, 6, 8]

In [101]:
df=pd.DataFrame({"Temperature":Temperature,"Performance":Performance})

In [102]:
df

Temperature  Performance
0           20            8
1           22            7
2           23            9
3           19            6
4           21            8

In [103]:
X=df[['Temperature']]
y=df['Performance']

In [104]:
from sklearn.linear_model import LinearRegression

In [105]:
LR=LinearRegression()

In [106]:
LR.fit(X,y)

LinearRegression()

In [107]:
## making prrediction for temperature 18 and 24

In [108]:
predict_data=pd.DataFrame({"Temperature":[18,24]})

In [109]:
LR.predict(predict_data)

array([6.1, 9.1])

15. Scenario: A study is conducted to compare the preferences of two groups of participants. The preferences are measured on a Likert scale from 1 to 5. The data collected is as follows:
- Group A: [4, 3, 5, 2, 4]
- Group B: [3, 2, 4, 3, 3]
- Perform a Mann-Whitney U test to determine if there is a significant difference in the median preferences between the two groups.

In [110]:
## H0:Median of Group A = Median of Group B
## H1=Median of Group A != Median of Group B

In [111]:
## Combine the data from both groups and assign ranks to the observations. In case of ties, assign the average rank. The combined data and ranks are as follows:
Data=[4, 3, 5, 2, 4, 3, 2, 4, 3, 3]
Ranks=[8, 3.5, 10, 1, 8, 3.5, 1, 8, 3.5, 3.5]

In [112]:
U_statistic_Group_A = 8 + 3.5 + 10 + 1 + 8
U_statistic_Group_B = 1 + 3.5 + 1 + 8 + 3.5

In [113]:
U_statistic_Group_A,U_statistic_Group_B

(30.5, 17.0)

In [114]:
## select minimum from two statistic
U_statistic_Group_B

17.0

In [115]:
## Calculate Expected Value
## EU = (n1 * (n1 + n2 + 1)) / 2
EU = (5 * (5 + 5 + 1)) / 2 

In [116]:
EU

27.5

In [117]:
## Calculte Standard Deviation
## std_U = sqrt((n1 * n2 * (n1 + n2 + 1)) / 12)
std_U = np.sqrt((5 * 5 * (5 + 5 + 1)) / 12)

In [118]:
## Calcute Z-score
z = (17 - 27.5) / 3.53

In [119]:
z

-2.974504249291785

In [120]:
## For significance level at 5%  two tailed 
critical_value=1.96

In [121]:
## In this case, the calculated z-score of -2.98 falls outside the range of ±1.96. Therefore, we reject the null hypothesis.

In [122]:
# there is a significant difference in the median preferences between Group A and Group B based on the Mann-Whitney U test at a 0.05 significance level

16. Scenario: A company wants to analyze the distribution of customer ages. The data collected is as follows:
- [25, 30, 35, 40, 45, 50, 55, 60, 65, 70]
- Calculate the interquartile range (IQR) of the ages

In [123]:
ages=[25, 30, 35, 40, 45, 50, 55, 60, 65, 70]

In [124]:
first_quartile=np.percentile(ages,25)

In [125]:
third_quartle=np.percentile(ages,75)

In [126]:
print(first_quartile,third_quartle)

36.25 58.75


In [127]:
interquaile_range=third_quartle-first_quartile

In [128]:
interquaile_range

22.5

17. Scenario: A study is conducted to compare the performance of three different machine learning algorithms. The accuracy scores for each algorithm are as follows:
- Algorithm A: [0.85, 0.80, 0.82, 0.87, 0.83]
- Algorithm B: [0.78, 0.82, 0.84, 0.80, 0.79]
- Algorithm C: [0.90, 0.88, 0.89, 0.86, 0.87]
- Perform a Kruskal-Wallis test to determine if there is a significant difference in the median accuracy scores between the algorithms

In [129]:
## H0:median_A = median_B = median_C
## H1: Medians are different

In [130]:
## Combine data and assigned rankes
CombinedData=[0.85, 0.80, 0.82, 0.87, 0.83, 0.78, 0.82, 0.84, 0.80, 0.79, 0.90, 0.88, 0.89, 0.86, 0.87]

In [131]:
Ranks= [11, 5, 7.5, 14, 9, 2, 7.5, 13, 5, 3, 15, 12, 10, 8, 9]

In [132]:
Sum_Ranks_A=11 + 5 + 7.5 + 14 + 9
Sum_Ranks_B = 2 + 7.5 + 13 + 5 + 3
Sum_Ranks_C = 15 + 12 + 10 + 8 + 9

In [133]:
## Calculate Test statistic
## H = [(12 * (R^2 - (n * (n + 1)^2) / 4)) / (n * (n + 1))]
H_statistic = (12 * ((46.5**2 + 30.5**2 + 54**2) - (15 * (15 + 1)**2) / 4)) / (15 * (15 + 1))

In [134]:
H_statistic

252.425

In [135]:
## Calculate Degree of freedom
df=3-1 ## 3 categories

In [136]:
df

2

In [137]:
## At significance level of 5% and df 2 we get crtical value
critical_value=5.991

In [138]:
if H_statistic>critical_value:
    print("we reject the null hypothesis and there is significant difference in the median accuracy scores between Algorithm A, Algorithm B, and Algorithm C")
else:
    print("We Accepth the null hypothesis")

we reject the null hypothesis and there is significant difference in the median accuracy scores between Algorithm A, Algorithm B, and Algorithm C


18. Scenario: A company wants to analyze the effect of price on sales. The data collected is as follows:
- Price (in dollars): [10, 15, 12, 8, 14]
- Sales: [100, 80, 90, 110, 95]
-Perform a simple linear regression to predictsales based on price


In [139]:
Price= [10, 15, 12, 8, 14]
Sales= [100, 80, 90, 110, 95]


In [140]:
df=pd.DataFrame({'Price':Price,'Sales':Sales})

In [141]:
df

Price  Sales
0     10    100
1     15     80
2     12     90
3      8    110
4     14     95

In [142]:
X=df[['Price']]
y=df['Sales']

In [143]:
from sklearn.linear_model import LinearRegression

In [144]:
LR=LinearRegression()

In [145]:
LR.fit(X,y)

LinearRegression()

In [146]:
predict_data=pd.DataFrame({'Price':[9,13]})

In [147]:
LR.predict(predict_data)

array([104.81707317,  90.79268293])

19. Scenario: A survey is conducted to measure the satisfaction levels of customers with a new product. The data collected is as follows:
- [7, 8, 9, 6, 8, 7, 9, 7, 8, 7]
- Calculate the standard error of the mean satisfaction score

In [148]:
data= [7, 8, 9, 6, 8, 7, 9, 7, 8, 7]

In [149]:
mean_data=np.mean(data)

In [150]:
mean_data

7.6

In [151]:
std_data=np.std(data)

In [152]:
std_data

0.9165151389911681

In [153]:
## Standard Error:std/sqrt(n)
standard_error=std_data/np.sqrt(len(data))

In [154]:
standard_error

0.28982753492378877

20. Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:
- Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]
- Sales (in thousands): [25, 30, 28, 20, 26]
- Perform a multiple regression analysis to predict sales based on advertising expenditure.

In [155]:
Advertising_Expenditure = [10, 15, 12, 8, 14]
Sales =  [25, 30, 28, 20, 26]

In [156]:
df=pd.DataFrame({"Advertising_Expenditure":Advertising_Expenditure,"Sales":Sales})

In [157]:
df

Advertising_Expenditure  Sales
0                       10     25
1                       15     30
2                       12     28
3                        8     20
4                       14     26

In [158]:
from sklearn.linear_model import LinearRegression

In [159]:
LR=LinearRegression()

In [160]:
X=df[['Advertising_Expenditure']]
y=df['Sales']

In [161]:
LR.fit(X,y)

LinearRegression()

In [162]:
predict_data=pd.DataFrame({'Advertising_Expenditure':[11,7]})

In [163]:
LR.predict(predict_data)

array([24.87804878, 20.26829268])